### ISSUE TITLE
`concordium-contracts-common`'s main has gone out of sync with `concordium-rust-smart-contracts` one

### ISSUE THREAD

**Issue by target-san** [Concordium/concordium-contracts-common#107]
**Description**

`concordium-contracts-common` and `concordium-rust-smart-contracts` seem out of sync in terms of development flow.
* CRSC's `main` references CCC's commit b65a4561dee10b2668a488cbd540f62d12fd99bc, while CCC's `main` is at 16e452154d7ef28a40cec317919bfe6f52d58056
* CCC is being upgraded in CRSC to its `main` only in branch [258-use-public-keys](https://github.com/Concordium/concordium-rust-smart-contracts/tree/258-use-public-keys), which seems to be long from being merged into `CRSC`'s `main`

This prevents other PRs which perform synced changes to both repos being correctly developed.

**Suggested fix**

* Create similar branch `258-use-public-keys` in CCC, set to 16e452154d7ef28a40cec317919bfe6f52d58056
* Make CRSC's `258-use-public-keys` branch reference similarly named branch in CCC
* Revert CCC's `main` to b65a4561dee10b2668a488cbd540f62d12fd99bc, making it in-sync with CRSC again

**Steps to Reproduce**

Check what CCC's commit is used as submodule in CRSC's `main`, and where's the actual CCC's `main` at

**Expected Result**

CCC's and CRSC's `main` branches are in sync

**Actual Result**

CCC's and CRSC's `main` branches are out of sync

**Versions**
N/A, concerns repository submodules

**Comment by abizjak** [comment]
That was a temporary issue since we had a lot of moving pieces at the same time.

The relevant PRs are merged now in concordium-rust-smart-contracts.
