### ISSUE TITLE
TransferFrom in SmartContracts

### ISSUE THREAD

**Issue by smh1001** [Concordium/concordium-contracts-common#39]
Smart contract approval allowance mechanism (Approving Allowances means authorizing the smart contract, in advance, to spend the tokens, without needing the private key to do that). ERC-20 has the TransferFrom method which does this. Source: Tacans

User stories
- (4) Add a description for "Ethereum Developers" on the documentation site

**Comment by abizjak** [comment]
This already exists in our CIS-1s standard.

The only remaining thing in this task is a guide to persons familiar with ERC20 or similar tokens to explain where the "missing" things are available. Some of this is already described in the standard as is.

**Comment by smh1001** [comment]
This epic has been superceded by "Concordium development for Ethereum developers" epic.
