### ISSUE TITLE
Add schema type for byte arrays in hex format

### ISSUE THREAD

**Issue by Bargsteen** [Concordium/concordium-contracts-common#40]
Add a schema type for byte arrays in hex format. They should be represented with a JSON string.

This is especially useful with the new cryptographic primitives: https://github.com/Concordium/concordium-rust-smart-contracts/pull/101

Will also require matching changes in cargo-concordium and concordium-client.

This will introduce a new contract schema version and require updating 
- Update in concordium-contracts-common
- Support in cargo-concordium
- Support in concordium-client
- Update contract schema documentation.
- Support in concordium-node-sdk-js

**Comment by limemloh** [comment]
This will be solved together with another addition to the schema.
The current state of this can be tracked at https://github.com/Concordium/concordium-wasm-smart-contracts/issues/53
