### ISSUE TITLE
Implement the Error for errors

### ISSUE THREAD

**Issue by limemloh** [Concordium/concordium-contracts-common#43]
Currently the errors in this crate does not implement the Error trait, which is expected when using the types outside of smart contracts (like the Rust SDK).

We have to ensure that implementing Error does not impact smart contract code, when building using no_std and if so, it should be moved behind a feature flag.

**Comment by abizjak** [comment]
Related to, and should be done together with https://github.com/Concordium/concordium-rust-smart-contracts/issues/76
