### ISSUE TITLE
Improve error reporting when serializing JSON using schema

### ISSUE THREAD

**Issue by Bargsteen** [Concordium/concordium-contracts-common#68]
**Description**

We could improve the error reporting when converting JSON parameters to binary using a schema in concordium-contracts-common. By improve, I mean that we could include a "stacktrace" to show where the incorrect value belongs. This is especially useful when the parameter is a struct or enum comprised of many fields.

So instead of giving the error `Expected AccountAddress`.
It should tell you this, but also include information about _where_ it expects an account address. Similar to what concordium-client does:
```
Error: Could not decode parameters from file 'param.json' as JSON:
       Expected value of type "<AccountAddress>", but got: 123.
       In [
           123
       ].
       In enum variant '"Account"'.
       In field 'operator'.
       In {
           "operator": {
               "Account": [
                   123
               ]
           },
           "update": {
               "Remove": []
           }
       }.
       In [
           {
               "operator": {
                   "Account": [
                       123
                   ]
               },
               "update": {
                   "Remove": []
               }
           }
       ].
```

Since the JavaScript SDKs recently started using concordium-contracts-common for handling the JSON to binary conversion, this issue has become more important.

**Comment by abizjak** [comment]
The `serial_value` method on `Type` now returns a meaningful error which can be rendered as a stack trace.
