### ISSUE TITLE
Implement `Deref` for `Owned*` to non-owned types (when Rust 1.65+)

### ISSUE THREAD

**Issue by Bargsteen** [Concordium/concordium-contracts-common#69]
**Description**

We have a few different types that have an owned and a reference version, fx `OwnedContractName`/`ContractName`, `OwnedEntrypointName`/`EntrypointName`.
Most of the useful methods are on the reference versions, and you can convert from the owned to the reference version via a method, fx `owned_contract_name.as_contract_name()`, and then use the useful methods there.

But it would be more ergonomic if we implemented `Deref` from the Owned to the reference version, so that you wouldn't need the conversion method.

However, we cannot implement Deref until we upgrade to Rust version 1.65+ which [introduces Generic Associated Types (GATs)](https://blog.rust-lang.org/2022/10/28/gats-stabilization.html). The issue is that we need to set the associated type `Target` to a type with a generic lifetime parameter: `type Target = ContractName<'a>`.

**Comment by abizjak** [comment]
So looking at this again, this won't really work since `Deref` has a defined interface and `Target` is not a GAT.

So how do we implement it?
```rust
impl ops::Deref for OwnedContractName {
    type Target = ContractName<'???>;

    fn deref(&self) -> &Self::Target {
      &self.as_contract_name()
    }
}
```

What to put inside `???`

**Comment by Bargsteen** [comment]
Hm, good point. Damn 😄
